# Generated by Django 5.2 on 2025-04-05 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_communities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_communities",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Showcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=7000)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech", "Technology"),
                            ("finance", "Finance"),
                            ("health", "Healthcare"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("retail", "Retail"),
                            ("manufacturing", "Manufacturing"),
                            ("real_estate", "Real Estate"),
                            ("transportation", "Transportation"),
                            ("energy", "Energy"),
                            ("agriculture", "Agriculture"),
                            ("hospitality", "Hospitality"),
                            ("construction", "Construction"),
                            ("legal", "Legal"),
                            ("marketing", "Marketing"),
                            ("media", "Media"),
                            ("non_profit", "Non-Profit"),
                            ("sports", "Sports"),
                            ("telecommunications", "Telecommunications"),
                            ("utilities", "Utilities"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="showcases",
                        to="core.community",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_showcases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcases",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
