# Generated by Django 5.2 on 2025-04-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="community",
            name="pin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
